name = "mortgage-explorer"
main = "src/main.tsx"
compatibility_date = "2024-01-01"


[[kv_namespaces]]
binding = "mortgage_explorer"
id = "fcf500d9f73f4502aac080d45a7f2967"

[assets]
directory = "./dist"
not_found_handling = "404-page"
# will serve dist/404.html (which copies over from public/404.html)

[build]
command = "npm run build"
